In [12]:
import torch
import math
from torch import nn

Pytorch tutorial: https://www.youtube.com/watch?v=c36lUUr864M&t=609s

In [ ]:
a = torch.tensor([[1],[2],[3]])
print(a)
print(a.shape)
b = a.expand([3,4])
print(b)

# can't do this
# c = a.expand(5, -1)
# print(c)
a= torch.tensor([[1,2,3,4]])
print(a)
print(a.shape)
b = a.expand(3,4)
print(b)

tensor([[1],
        [2],
        [3]])
torch.Size([3, 1])
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])
tensor([[1, 2, 3, 4]])
torch.Size([1, 4])
tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])


In [ ]:
a = torch.tensor([1,2,3,4])
print(a)
print(a.shape)

b = a.unsqueeze(1)
print(b)
print(b.shape)


c = a.unsqueeze(0)
print(c)
print(c.shape)

tensor([1, 2, 3, 4])
torch.Size([4])
tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1])
tensor([[1, 2, 3, 4]])
torch.Size([1, 4])


In [ ]:
#triangular matrix
a = torch.rand(5,5)
print(a)

b = torch.tril(a, 0)
print(b)

c = torch.tril(a,1)
print(c)

d = torch.tril(a,-1)
print(d)

tensor([[0.3437, 0.2040, 0.0133, 0.2977, 0.8172],
        [0.1891, 0.3527, 0.3202, 0.4193, 0.2062],
        [0.7198, 0.9234, 0.4747, 0.6147, 0.7170],
        [0.8782, 0.3959, 0.1477, 0.4709, 0.5021],
        [0.5164, 0.7162, 0.0572, 0.2622, 0.5583]])
tensor([[0.3437, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1891, 0.3527, 0.0000, 0.0000, 0.0000],
        [0.7198, 0.9234, 0.4747, 0.0000, 0.0000],
        [0.8782, 0.3959, 0.1477, 0.4709, 0.0000],
        [0.5164, 0.7162, 0.0572, 0.2622, 0.5583]])
tensor([[0.3437, 0.2040, 0.0000, 0.0000, 0.0000],
        [0.1891, 0.3527, 0.3202, 0.0000, 0.0000],
        [0.7198, 0.9234, 0.4747, 0.6147, 0.0000],
        [0.8782, 0.3959, 0.1477, 0.4709, 0.5021],
        [0.5164, 0.7162, 0.0572, 0.2622, 0.5583]])
tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1891, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.7198, 0.9234, 0.0000, 0.0000, 0.0000],
        [0.8782, 0.3959, 0.1477, 0.0000, 0.0000],
        [0.5164, 0.7162, 0.0572, 0.2622, 0.0000

In [ ]:
a = torch.tril(torch.ones((10,10)))

print(a)
print(a.shape)

b = a.expand(5, 1, 10, 10)

print(b)
print(b.shape)

In [ ]:
a = torch.rand((3,3,3))
print(a.shape)

b = a.reshape(-1)
print(b.shape)

c = a.reshape((-1, 3))
print(c.shape)

torch.Size([3, 3, 3])
torch.Size([27])
torch.Size([9, 3])


In [ ]:
print(a.dim())

3


In [ ]:
a = torch.normal(0,1,(2,2,2))

print(a.shape)
print(a)

torch.Size([2, 2, 2])
tensor([[[-0.8517, -0.9505],
         [ 1.8307,  1.0143]],

        [[-1.0388, -0.6974],
         [-1.0601,  0.7165]]])


In [ ]:
a = torch.rand((3,3))
print(a)
print(a.shape)

b = a.unsqueeze(-1)

print(b.shape)


tensor([[0.6331, 0.5684, 0.4321],
        [0.8637, 0.2813, 0.7978],
        [0.4593, 0.7090, 0.9263]])
torch.Size([3, 3])
torch.Size([3, 3, 1])


In [ ]:
a = torch.rand((3,4))
print(a.shape)

print(a)

b = torch.permute(a, (1,0))
print(b.shape)

print(b)

torch.Size([3, 4])
tensor([[0.6328, 0.4418, 0.6276, 0.6238],
        [0.3207, 0.6076, 0.6806, 0.4922],
        [0.8170, 0.5777, 0.4036, 0.7797]])
torch.Size([4, 3])
tensor([[0.6328, 0.3207, 0.8170],
        [0.4418, 0.6076, 0.5777],
        [0.6276, 0.6806, 0.4036],
        [0.6238, 0.4922, 0.7797]])


In [ ]:
a = torch.rand(2,3)
print(a.shape)

b = a.reshape(2,3,-1)

print(b.shape)

torch.Size([2, 3])
torch.Size([2, 3, 1])


In [ ]:
#Play with masked softmax operation 
valid_lens = torch.tensor([2,3])
print(valid_lens)
print(valid_lens[:, None])
print(valid_lens.shape)
print(torch.arange((10), dtype = torch.float32)[None, :])

a = torch.arange((10), dtype = torch.float32)[None, :] < valid_lens[:, None]
print(a)

tensor([2, 3])
tensor([[2],
        [3]])
torch.Size([2])
tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[ True,  True, False, False, False, False, False, False, False, False],
        [ True,  True,  True, False, False, False, False, False, False, False]])
tensor([2, 2, 3, 3])
tensor([2, 3])
torch.Size([2])


In [ ]:
a = torch.tensor([[1,2,3,4],[5,6,7,8], [8,9,10,11]])
print(a.shape)
print(torch.repeat_interleave(a, 3, dim = 1))
print(a.reshape(-1))

X = torch.rand(2,2,4)
X = X.reshape(-1)
print(X)
print(X.shape)
X = X.reshape(-1, X.shape[-1])
print(X)
print(X.shape)

valid_len = torch.tensor([3])
a = torch.arange((10))[None, :] < valid_len[:, None]
print(a)

torch.Size([3, 4])
tensor([[ 1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4],
        [ 5,  5,  5,  6,  6,  6,  7,  7,  7,  8,  8,  8],
        [ 8,  8,  8,  9,  9,  9, 10, 10, 10, 11, 11, 11]])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10, 11])
tensor([0.1903, 0.9261, 0.9347, 0.2305, 0.6715, 0.4695, 0.3586, 0.3648, 0.3117,
        0.1438, 0.7858, 0.9161, 0.8495, 0.3801, 0.1596, 0.8199])
torch.Size([16])
tensor([[0.1903, 0.9261, 0.9347, 0.2305, 0.6715, 0.4695, 0.3586, 0.3648, 0.3117,
         0.1438, 0.7858, 0.9161, 0.8495, 0.3801, 0.1596, 0.8199]])
torch.Size([1, 16])
tensor([[ True,  True,  True, False, False, False, False, False, False, False]])


In [ ]:
hidden = 6
batch = 10
kv_pair = 4 
heads = 2

a = torch.rand(kv_pair, hidden)
print(a.shape)
print(a)

b = a.reshape(kv_pair, heads, hidden // heads)

print(b.shape)
print(b)

c = b.permute(1,0,2)

print(c.shape)

print(c)


torch.Size([4, 6])
tensor([[0.3904, 0.3296, 0.5068, 0.8231, 0.5633, 0.8274],
        [0.0826, 0.3159, 0.7305, 0.9660, 0.7014, 0.6434],
        [0.7574, 0.4168, 0.6408, 0.5765, 0.4846, 0.1469],
        [0.4626, 0.1326, 0.7596, 0.2471, 0.5257, 0.6179]])
torch.Size([4, 2, 3])
tensor([[[0.3904, 0.3296, 0.5068],
         [0.8231, 0.5633, 0.8274]],

        [[0.0826, 0.3159, 0.7305],
         [0.9660, 0.7014, 0.6434]],

        [[0.7574, 0.4168, 0.6408],
         [0.5765, 0.4846, 0.1469]],

        [[0.4626, 0.1326, 0.7596],
         [0.2471, 0.5257, 0.6179]]])
torch.Size([2, 4, 3])
tensor([[[0.3904, 0.3296, 0.5068],
         [0.0826, 0.3159, 0.7305],
         [0.7574, 0.4168, 0.6408],
         [0.4626, 0.1326, 0.7596]],

        [[0.8231, 0.5633, 0.8274],
         [0.9660, 0.7014, 0.6434],
         [0.5765, 0.4846, 0.1469],
         [0.2471, 0.5257, 0.6179]]])


In [ ]:
X = torch.arange(10).reshape(-1, 1)
P = torch.zeros((1, 1000, 32))

print(P.shape)

X = torch.arange(10,20, 2)
print(X)

torch.Size([1, 1000, 32])
tensor([10, 12, 14, 16, 18])


In [11]:
emb = nn.Embedding(5000, 24)

X = torch.ones((2,100), dtype=torch.long)
Y = emb(X)
print(Y.shape)
X = torch.ones((2,100,24), dtype=torch.long)
Y = emb(X)
print(Y.shape)

torch.Size([2, 100, 24])
torch.Size([2, 100, 24, 24])
